### ISSUE TITLE
Scrubs 2 YouTube api.

### ISSUE THREAD

**Issue by Greg0580** [jewbmx/jewbmx.github.io#12]
This I a question.  In Account settings, there is YouTube API. 
Witch API do I enter?  Is it API Key,  Or API ID, Or Api Secret . Please sorry to be a pain.

**Comment by jewbmx** [comment]
I dont remember the answer to that one lol i personally just leave it blank and also rely more on tmdb and imdb for the trailers which seems to bypass key use if i recall. If i also recall properly the code might still be setup to randomly use a couple default api's instead of just one to keep things goin.

I will look into it by morning and let you know if someone else doesnt answer this first 😉

**Comment by Greg0580** [comment]
Allgood  and if you do can add it to show api id etc.
Like YouTube ID and or API: ID etc.
Thank you for your time.  Much appreciated.



Sent from my Galaxy



-------- Original message --------
From: jewbmx ***@***.***>
Date: 28/02/23 15:39 (GMT+12:00)
To: "jewbmx/jewbmx.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jewbmx/jewbmx.github.io] Scrubs 2 YouTube api. (Issue #12)


I dont remember the answer to that one lol i personally just leave it blank and also rely more on tmdb and imdb for the trailers which seems to bypass key use if i recall. If i also recall properly the code might still be setup to randomly use a couple default api's instead of just one to keep things goin.

I will look into it by morning and let you know if someone else doesnt answer this first 😉

**Comment by jewbmx** [comment]
K so that would be api key. First the addon tries to pull this key from your plugin.video.youtube settings, then if that fails it tries to get it from my addons settings, then if that fails  it randomly chooses one from the 2 i coded into the addon lol.
This whole bit is also only used for youtube based trailer searches. Meaning your source can be set to imdb or tmdb and youtube api wont be used, which are honestly the better trailer choices most the time and my recent changes makes it so you can easily bounce between em without much effort.

**Comment by Greg0580** [comment]
Thank you.   Much appreciated.



Sent from my Galaxy



-------- Original message --------
From: jewbmx ***@***.***>
Date: 1/03/23 00:39 (GMT+12:00)
To: "jewbmx/jewbmx.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jewbmx/jewbmx.github.io] Scrubs 2 YouTube api. (Issue #12)


K so that would be api key. First the addon tries to pull this key from your plugin.video.youtube settings, then if that fails it tries to get it from my addons settings, then if that fails it randomly chooses one from the 2 i coded into the addon lol.
This whole bit is also only used for youtube based trailer searches. Meaning your source can be set to imdb or tmdb and youtube api wont be used, which are honestly the better trailer choices most the time and my recent changes makes it so you can easily bounce between em without much effort.
