### ISSUE TITLE
My stuff items doesn't display posters

### ISSUE THREAD

**Issue by rahaaatul** [jewbmx/jewbmx.github.io#13]
I created a widget on my home from my stuff > trakt > TV shows > Progress. It doesn't show posters for the items only low quality pictures.

_I'll post screenshots later._

**Comment by rahaaatul** [comment]
I looked at it again. I made a mistake, it was supposed to show episode thumbnail?
Is there a way to change it to show episodes season poster?

**Comment by jewbmx** [comment]
Dont know anything about your problem or your style of use, but the addons all coded to work as is, your tinkering would need to be figured out on you end with whatever settings wherever lol. Id maybe check the kodi settings or skin settings and see if one of those settings can do what your wanting or something. Personally not interested in trying to hard code this sorta thing into the addon tho.

**Comment by rahaaatul** [comment]
I want it like this (TMDB Helper Widget) - 
![Screenshot (86)](https://user-images.githubusercontent.com/86149861/222886693-8f483c24-5948-4426-95fb-0fd89aa90ed4.png)

But it shows like this - 
![Screenshot (87)](https://user-images.githubusercontent.com/86149861/222886733-e4969a93-f078-4747-988c-2feaa8ea9857.png)

And then  if you click on it, instead of playing the episode, it goes to episode list
https://user-images.githubusercontent.com/86149861/222886670-78266ff9-a6ad-4099-b890-3215c995bcc3.mp4

**Comment by phill-nz** [comment]
completely unlivable 

i do not know how you will survive

**Comment by jewbmx** [comment]
Looks and sounds like your wanted option is your list in the tv show form as in a list of shows before the episodes list and what you get is the episode list lol.
Regardless it appears you already have what you want so i dont know why your requesting a new feature lmao. Just use your little extended info mod like you seem to be using already.

**Comment by rahaaatul** [comment]
That's not the issue. Issue is, it doesn't display the poster, it displays the episodes thumbnail, but when you click on it, it takes you to episodes list of that show.

And also I want to scrubs widget because it will directly find the media and play it. Whereas with tmdb you have to select the player if the file isn't stored locally.

**Comment by jewbmx** [comment]
Thats two completely different addons lol and two completely different trakt designs. If you have cinetrak on your phone or probably any trakt app you can open it up and see the difference pretty easily. When you click on "my shows" it will load your watchlist as you like it in tv show form which is the way your first picture is and the most commonly used trakt layout counting their own site. But once you click a show to go one step further it shows you the episode progress like next episode to watch and next to air or whatnot. This is where addons like scrubs trakt use pretty much is seen aka your 2nd pic lol. I think the closest option that you can use that comes close to your first pic is the collections feature. 
As for me and you and scrubs, if i was to add in your request id likely have to rewrite/write a trakt feature/section that just grabs the tv show list from your "progress" then load it that way instead of it going ahead and doing the episode grabbing next step lol.

Or a ghetto option to just change the artwork for every episode to be the tvshow image for ya lol but im guessing that would also need me to code in the tvshow style viewtype instead of it being episodes as it is which makes the pic that way with the little plot and shit lmao.

**Comment by jewbmx** [comment]
I looked into the alternative options like the kodi setting in media to turn off episode thumbs but that just does the fanart as a replacement lol so i guess if you would like that ghetto artwork setting added in that i spoke of at the end of my last response i can probably toss it in for ya. I could probably do the other idea as well making another progress list in show form too if ya really want em lol

**Comment by jewbmx** [comment]
Welp your lack of response and feedback has made me decide to say fuck ya and move on lol.
Your odd little setting has been added in now as a general setting for all episode based items. Hope it works yet dont really care since you been oh so helpful in its production lol.

**Comment by rahaaatul** [comment]
Hey there!
First thing first, I apologize for my lack of response, I was busy. Secondly, are you okay? No need to act like this.
And thank you, for adding it, I just saw this email now, I had no idea you added it, I thought you weren't gonna add it, because you were against it. But I'll try it later, I'm away from my PC now.

Good day to you @jewbmx

**Comment by phill-nz** [comment]
im staying out of this one .. you do a fantastic job keeping scrubs going well .. i can never thank you enough for what you do
