### ISSUE TITLE
Trakt Userlists

### ISSUE THREAD

**Issue by rogermae** [jewbmx/jewbmx.github.io#6]
Hi  Scrubs v2 v5.0.13 My Stuff/My Userlists/TV Show Userlists
When accessing this section it shows duplicate entries of your lists but none of them will open. However when accessing My Movies userlists, it opens, no problem. Revoked, closed and reauthorized Trakt to no avail.

**Comment by jewbmx** [comment]
Thats a known issue i am gonna look into soon. The dupes are due to how its currently coded and how trakt lists work, once i dig into the error im also gonna reorganize/redesign the userlist section to help prevent the dupes and bring a little closer to my ocd.

**Comment by jewbmx** [comment]
My progress is a bit slow lately so i figured id post a half assed fix incase you or anyone else is waiting for this to work again and/or rely on the userlists.
Movies and shows seem to load fine-ish if you clear all cache and only click one of the types, (shows only or movies.)  My lists work if thats done which makes me think the cache code added in is causing problems right now. The episode list option never seems to work for me so it probably needs much more work lol.
Also to be clear this is a half assed fix and not completely tested because of the glitchy outcome always changing lol so no promises that it will always work.
Imma try to get into it properly and fix everything still so waiting isnt a bad option either.
